name: "[Manual] Create Media JSON and Thumbnails from Scratch"

# 1. 수동 실행(workflow_dispatch) 전용으로 설정
on:
  workflow_dispatch:

jobs:
  build-and-rebuild-all:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.XTX9_PAT }}

      - name: Install ImageMagick
        run: sudo apt-get update && sudo apt-get install -y imagemagick

      # 2. 'imgs' 폴더 내의 모든 이미지 파일 찾기 (기존 썸네일 제외)
      - name: Find all image files
        id: find_images
        run: |
          echo "::set-output name=files::$(find imgs -type f -iregex '.*\.\(jpg\|jpeg\|png\|gif\)$' ! -name '*-thumb.*' | tr '\n' ' ')"

      # 3. 찾은 모든 이미지에 대해 썸네일 생성
      - name: Generate all thumbnails
        if: steps.find_images.outputs.files != ''
        run: |
          for file in ${{ steps.find_images.outputs.files }}; do
            echo "Generating thumbnail for $file"
            thumb_file=$(echo "$file" | sed -E 's/\.(jpg|jpeg|png|gif)$/-thumb.&/')
            # 덮어쓰기를 위해 기존 썸네일이 있어도 재생성
            convert "$file" -resize 300x "$thumb_file"
          done

      # 4. 전체 JSON 파일 생성 (기존 스크립트 재활용)
      - name: Setup PHP and Generate JSON
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.1"
          extensions: curl
      - run: php generate-json.php # 이 스크립트는 항상 전체를 스캔하므로 그대로 사용

      # 5. 모든 변경사항(썸네일, JSON) 커밋 및 푸시
      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add .
          if ! git diff --staged --quiet; then
            git commit -m "Chore: Rebuild all thumbnails and media list [skip ci]"
            git push
          else
            echo "No changes to commit."
          fi
