# 워크플로우 이름
name: Generate Media List JSON

# main 브랜치에 push가 발생할 때마다 실행
on:
  push:
    branches:
      - main
  # 수동 실행도 가능하도록 workflow_dispatch 추가
  workflow_dispatch:

# 작업 정의
jobs:
  build-and-deploy:
    # ubuntu 최신 버전에서 실행
    runs-on: ubuntu-latest

    # [수정] 이 블록을 추가하여 gh-pages 브랜치에 쓸 수 있는 권한을 부여합니다.
    permissions:
      contents: write

    # 단계별 실행 내용
    steps:
      # 1. 저장소 코드 체크아웃
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. PHP 환경 설정 (shivammathur/setup-php 사용)
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          # cURL 확장이 필요하므로 활성화
          extensions: curl
          # [수정] 지원하지 않는 'jit' 옵션을 삭제합니다.
          # jit: false <-- 이 줄을 삭제했습니다.

      # 3. PHP 스크립트 실행하여 media-list.json 생성
      - name: Generate JSON file
        run: php generate-json.php

      # 4. 생성된 JSON 파일을 GitHub Pages로 배포
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          # media-list.json 파일만 배포하도록 수정하여 더 안전하게 만듭니다.
          publish_dir: .
          # force_orphan: true 옵션을 추가하여 매번 깨끗한 브랜치에서 시작하도록 합니다.
          force_orphan: true
          # 배포 커밋을 할 유저 정보
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
          # 커밋 메시지
          commit_message: 'Deploy generated media-list.json'