name: Generate Thumbnails and Media List

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          # 봇이 푸시하려면 Personal Access Token(PAT)이 필요합니다.
          token: ${{ secrets.XTX9_PAT }} 

      # 1. 이미지 처리 도구 설치
      - name: Install ImageMagick
        run: sudo apt-get update && sudo apt-get install -y imagemagick

      # 2. 변경된 이미지 파일 목록 찾기
      - name: Find new/modified images
        id: find_images
        # 이전 커밋과 비교하여 추가/수정된 이미지 파일 목록만 추출
        run: |
          echo "::set-output name=files::$(git diff --name-only --diff-filter=AM ${{ github.event.before }} ${{ github.event.after }} | grep -E '\.(jpg|jpeg|png|gif)$' | tr '\n' ' ')"

      # 3. 썸네일 생성
      - name: Generate thumbnails
        if: steps.find_images.outputs.files != ''
        run: |
          for file in ${{ steps.find_images.outputs.files }}; do
            if [[ ! "$file" == *"-thumb."* ]]; then # 썸네일 파일 자체는 건너뛰기
              echo "Generating thumbnail for $file"
              # 원본 파일명에서 확장자를 제외하고 '-thumb'를 붙여 썸네일 파일명 생성
              thumb_file=$(echo "$file" | sed -E 's/\.(jpg|jpeg|png|gif)$/-thumb.&/')
              # ImageMagick을 사용하여 썸네일 생성 (가로 300px, 세로 비율 유지)
              convert "$file" -resize 300x "$thumb_file"
            fi
          done

      # 4. JSON 파일 생성 (기존 generate-json.php 실행)
      - name: Setup PHP and Generate JSON
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          extensions: curl
      - run: php generate-json.php

      # 5. 변경사항(생성된 썸네일, JSON) 커밋 및 푸시
      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add . # 모든 변경사항(썸네일, JSON) 추가
          # 변경사항이 있을 때만 커밋
          if ! git diff --staged --quiet; then
            git commit -m "Chore: Generate thumbnails and update media list [skip ci]"
            git push
          else
            echo "No changes to commit."
          fi