name: Generate Media List JSON (Incremental Update)

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        # 전체 히스토리를 가져와야 diff가 가능합니다.
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          extensions: curl

      # 1. 이전 버전의 JSON 파일을 gh-pages 브랜치에서 다운로드 (캐시 역할)
      - name: Download previous JSON
        # || true를 붙여 파일이 없는 첫 실행 시 오류가 나지 않도록 합니다.
        run: |
          curl -s -f -o old-media-list.json "https://raw.githubusercontent.com/${{ github.repository }}/gh-pages/xtx9-media-storage-media.json" || true
      
      # 2. 이전 커밋과 현재 커밋 사이의 변경된 파일 목록 생성
      - name: Get changed files
        # workflow_dispatch로 수동 실행 시에는 전체를 다시 생성하도록 합니다.
        if: github.event_name == 'push'
        run: |
          git diff --name-status ${{ github.event.before }} ${{ github.event.after }} | grep '^imgs/' > changes.txt
          echo "Found changes:"
          cat changes.txt
      - name: Handle manual trigger (full rebuild)
        if: github.event_name == 'workflow_dispatch'
        run: echo "Manual trigger detected, forcing full rebuild." > changes.txt

      # 3. 변경사항을 기반으로 JSON 업데이트
      - name: Update JSON based on changes
        run: php update-json.php changes.txt old-media-list.json

      # 4. 생성된 JSON 파일을 GitHub Pages로 배포
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: .
          # 새 JSON 파일만 배포하도록 명시
          file_pattern: xtx9-media-storage-media.json
          force_orphan: true
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
          commit_message: 'Update media-list.json'