name: Trigger Media Storage Init Workflow

on:
  push:
    branches:
      - main # 또는 주력 브랜치 이름 (예: master)
    paths:
      - "imgs/**" # imgs 폴더와 그 하위의 모든 파일/폴더 변경 감지

jobs:
  trigger-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger xtx9/action workflow
        run: |
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.CROSS_REPO_PAT }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/xtx9/action/actions/workflows/xtx9-media-storage-init.yml/dispatches \
            -d '{"ref":"main"}' # action 리포지토리의 main 브랜치에 있는 워크플로우를 실행
